{% set name = "nidaqmx" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ni/nidaqmx-python/archive/{{ version }}.tar.gz
  sha256: f3d3df29ccfbb4f278648f101efde475f66a0c306fde918c06679dd323574f5b

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - six
    - enum34  # [py<34]

test:
  imports:
    - nidaqmx

about:
  home: https://github.com/ni/nidaqmx-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python API for interacting with NI-DAQmx'
  description: |
    The nidaqmx package contains an API (Application Programming Interface) for
    interacting with the NI-DAQmx driver. The package is implemented in Python.
    This package was created and is supported by NI. The package is implemented
    as a complex, highly object-oriented wrapper around the NI-DAQmx C API using
     the ctypes Python library.
  doc_url: http://nidaqmx-python.readthedocs.io/en/latest/
  dev_url: https://github.com/ni/nidaqmx-python

extra:
  recipe-maintainers:
    - carlodri
    - lstebel
