# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bXEG0dimqMLBQOAC0So/ujyKSVTKQtZKHKi3L8+6zKstB23UX3TULqIYv5pmzm4GBfdP8zmU2VhjKkQjMNIpztemAPeZ88cPZDNfQB3HKfg9+me3/y3LPeyht7WN3eefBtXcyZxT03sUdf3t9DNoSMph+ddsmCLwuNTWJCWSWekW7vOVBYO6NdC7jzz+mQCXfcYhq05TIAc7GcmVJ9edAGRf+SDKCkMmcf1NUJRi6CMa5QGqdI5DITxlWeMmYdVOlxzmKHpPbTDx/Hqyl0Xd8bLOsmzbO27dIFqUwgnW6TR6YxIcMjIo9Xhx+2o1+JtDdxzVSseI5DuTWOqWMXf5ENHiTQSt2V2uZUUjQcmFoD422RmGOfR8tri7S7Hq06l7pZhj1VRw5FlObE7PBRhC760eHdVW1RXWfAh332HywOiGVXSthfyVX6Cxnq5cm7WOAhtLk7u7t4EzICayaMJcgOmYcnMNSSz9fmxgw2W0ZDc15lhA90ootwaxUBC3FyPOBJ/YvGxYesfm2E8qh7IaIwDd7EpyaT3wmuMVPubqdtXkvYjgmfxWahNAJ8XHWXcEVkvXexPjSbt78WAPjPT6HbBmkji4bO50YPi5nY/rS7lCznZhrhh9el2AQpI+no+d0EMx/5/gi10sf4t+y9GH38eNMeuHqq7vdX2wMUpDttM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
