appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bXEG0dimqMLBQOAC0So/ujyKSVTKQtZKHKi3L8+6zKstB23UX3TULqIYv5pmzm4GBfdP8zmU2VhjKkQjMNIpztemAPeZ88cPZDNfQB3HKfg9+me3/y3LPeyht7WN3eefBtXcyZxT03sUdf3t9DNoSMph+ddsmCLwuNTWJCWSWekW7vOVBYO6NdC7jzz+mQCXfcYhq05TIAc7GcmVJ9edAGRf+SDKCkMmcf1NUJRi6CMa5QGqdI5DITxlWeMmYdVOlxzmKHpPbTDx/Hqyl0Xd8bLOsmzbO27dIFqUwgnW6TR6YxIcMjIo9Xhx+2o1+JtDdxzVSseI5DuTWOqWMXf5ENHiTQSt2V2uZUUjQcmFoD422RmGOfR8tri7S7Hq06l7pZhj1VRw5FlObE7PBRhC760eHdVW1RXWfAh332HywOiGVXSthfyVX6Cxnq5cm7WOAhtLk7u7t4EzICayaMJcgOmYcnMNSSz9fmxgw2W0ZDc15lhA90ootwaxUBC3FyPOBJ/YvGxYesfm2E8qh7IaIwDd7EpyaT3wmuMVPubqdtXkvYjgmfxWahNAJ8XHWXcEVkvXexPjSbt78WAPjPT6HbBmkji4bO50YPi5nY/rS7lCznZhrhh9el2AQpI+no+d0EMx/5/gi10sf4t+y9GH38eNMeuHqq7vdX2wMUpDttM=}
